### ISSUE TITLE
Upgrade to Cromwell 34 

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#113]
Timeline: Cromwell 34 released this week. Available for FireCloud release anytime thereafter. Ideally week of 7/23 

To Do for This Release: 
- [ ] update rawls' dependency on `wdl-draft2` jar to cromwell 34 version; make code changes for compatibility as necessary
- [ ] update agora's dependency on `wdl-draft2` jar to cromwell 34 version; make code changes for compatibility as necessary
- [ ] update firecloud-develop to point at cromwell 34 docker hash
- [ ] update cromwell conf to enable PAPI v2 back end, but leave PAPI v1 as the default. Context: PAPI v2 will be unused by FireCloud in the short term, but may be poked at manually by developers in the prod env. See Cromwell 32 release notes for info on configuring PAPI v2: https://github.com/broadinstitute/cromwell/releases/tag/32, and follow broadinstitute/rawls#963 for it being enaled in FireCloud
- [ ] update cromwell conf for demo DOS url support
- [ ] smoke test in a fiab
- [ ] perf/scale/stability acceptance test in the perf env

see https://docs.google.com/document/d/1EEzwemE8IedCplIwL506fiqXr0262Pz4G0x6Cr6V-5E/edit for more details.
