### ISSUE TITLE
Accepting Cromwell 32 w/out WDL 1.0 

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#76]
- [x] Diff firecloud-develop's `/base-configs/cromwell/cromwell.conf.ctmpl` against cromwell's `/core/src/main/resources/reference.conf` and `/cromwell.examples.conf`. For any notable diffs, discuss with the Cromwell|Workbench teams and resolve.
- [x] Agora PR to adopt new cromwell jar: broadinstitute/agora#259
- [x] Rawls PR to adopt new cromwell jar: broadinstitute/rawls#933
- [x] firecloud-develop branch - and PR against perf - to include the rawls and agora branches above plus update cromwell docker image: see https://github.com/broadinstitute/firecloud-develop/commit/6f2bf8db36f8e7b5d746450fe9612b19aef9ee7e, which was reverted
- [x] stand up a fiab with C32 and test manually and/or run automation?
- [x] test on perf environment
- [x] merge to dev environment and test there
- [ ] update https://docs.google.com/document/d/1EEzwemE8IedCplIwL506fiqXr0262Pz4G0x6Cr6V-5E/edit with any learnings from above
---

Accept 32 (without WDL 1.0 support) 
- standing up env, tests, etc. 

Out of scope (for future around mid-June in a separate issue): 
- Accept 33 
- with WDL 1.0 
- will include scala updating in rawls and agora 

Notes:
- connect with Andrew on implementation
- DO NOT GO OUT before/ at same time as read-only Cromwell. Ensure read-only goes out to production in advance before pushing this to perf for testing 
- Release after FC workshop on Wednesday (6/6) to avoid conflict with workshop materials and compatibility 

Release notes: 

**GPU**
The PAPI backend now supports specifying GPU through WDL runtime attributes:

runtime {
    gpuType: "nvidia-tesla-k80"
    gpuCount: 2
    zones: ["us-central1-c"]
}
The two types of GPU supported are nvidia-tesla-k80 and nvidia-tesla-p100

Important: Before adding a GPU, make sure it is available in the zone the job is running in: https://cloud.google.com/compute/docs/gpus/

**Read Limits**
File read limits have been introduced to help maintain Cromwell stability across all users. 

**Task Retries**
Cromwell now supports retrying failed tasks up to a specified count by declaring a value for the maxRetries key through the WDL runtime attributes. This retry option is introduced to provide a strategy for tackling transient job failures. For example, if a task fails due to a timeout from accessing an external service, then this option helps re-run the failed the task without having to re-run the entire workflow. It takes an Int as a value that indicates the maximum number of times Cromwell should retry a failed task. This retry is applied towards jobs that fail while executing the task command.
If using the Google backend, it's important to note that The maxRetries count is independent from the preemptible count. For example, the task below can be retried up to 6 times if it's preempted 3 times AND the command execution fails 3 times.
runtime {
  preemptible: 3
  maxRetries: 3
}
Defaults to 0.
